name: MMP2.0-BO Tests
on:
  push:
    branches: [ main ]
pull_requests:
  branches: [ main ]
schedule:
  - cron: '30 1 * * 1-5'
workflow_dispatch:
repository_dispatch:
  types: [ trigger-workflow ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4
    - uses: action/setup-node@v4
    - name: Install dependencies
    run: npm ci
    - name: Install Playwright Browsers
    run: npx palywright install --with-deps
    - name: Run Playwright tests
    run: npx playwright test
    -uses: actions/upload-artifact@v4
    if: always()
    with:
      name: playwright-report
      path: playwright-report/
      retention-days: 30